config/routes.rb
TwitterClone::Application.routes.draw do
  
  resources :sessions
  resources :users do
    member do
      get :following, :followers
    end    
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root :to => 'StaticPages#home'
 
  match "/users/:id/confirm/:confirm_id", to:"users#confirm", as: :confirm
  match "/signup",  to:"users#new"
  match "/signin",  to:"sessions#new"
  match "/signout", to:"sessions#destroy"

  match "/home", to:"static_pages#home"
  match "/about", to:"static_pages#about"
  match "/help", to:"static_pages#help"
  match "/contact", to:"static_pages#contact"
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts, dependent: :destroy
	has_many :relationships, foreign_key:"follower_id", dependent: :destroy
	has_many :followed_users, through: :relationships, source:"followed"

	has_many :reverse_relationships, class_name:Relationship, foreign_key:"followed_id", dependent: :destroy
	has_many :followers, through: :reverse_relationships, source:"follower"


	before_save { |user| user.email = user.email.downcase }
	before_save :create_a_rememberme_token
	
	has_secure_password

	attr_accessible :email, :name, :password, :password_confirmation
	validates :name, 	presence:true, length:{ maximum:50 }
	VALID_EMAIL_REGEX = /\A[\w\-.+]+@[a-z\d.]+\.[a-z]+\z/i
	validates :email, 	presence:true, 
						format:VALID_EMAIL_REGEX, 
						uniqueness:{ case_sensitive:false }
	validates :password, length:{ minimum:6 }
	validates :password_confirmation, presence:true


	
	def feed
		Micropost.from_users_followed_by(self)
	end

	def follow!(user)
		relationships.create!(followed_id:user.id)
	end

	def unfollow(user)
		relationships.find_by_followed_id(user.id).destroy
	end

	def following?(user)
		relationships.find_by_followed_id(user.id)
	end

	def send_email_confirmation
		generate_token(:confirmation_code)
		self.confirmation_code_send_at = Time.zone.now
		self.email_confirmed = false
		save!(:validate => false)
		UserMailer.email_confirmation(self).deliver
	end

	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end
	
	private

	def create_a_rememberme_token				
		self.rememberme_token = SecureRandom.urlsafe_base64
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :check_whether_the_user_is_signed_in, only: [ :index, :show, :edit, :update, :destroy, :following, :followers]
	before_filter :check_whether_correct_user, only: [:edit, :update]
	before_filter :check_whether_admin, only:[:destroy]

	def index
		@users = User.page(params[:page])
	end
  
	def show
		@user = User.find(params[:id])
		@microposts = @user.microposts.paginate(page: params[:page])		
	end

	def new
		@user = User.new
	end

	def create		
		@user = User.new(params[:user])
		
		if @user.save
			signin_in @user
			@user.send_email_confirmation
			flash[:success] = "You have successfully registered"
			flash[:notice] = "An email as send with instruction to complete registration"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
			
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			signin_in @user
			flash[:success] = "You profile has been successfully updated"
			redirect_to @user
		else
			render 'edit'
		end
		
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User destroyed"
		redirect_to users_path
	end

	def following
		@title = "following"
		@user = User.find(params[:id])
		@users = @user.followed_users.paginate(page: params[:page])
		render 'show_follow'
	end

	def followers
		@title = "followers"
		@user = User.find(params[:id])
		@users = @user.followers.paginate(page: params[:page])
		render 'show_follow'
	end

	def confirm
		@user = User.find_by_confirmation_code(params[:confirm_id])
		if @user && @user.confirmation_code_send_at > 2.hours.ago
			@user.toggle!(:email_confirmed)
			@user.confirmation_code = nil
			@user.confirmation_code_send_at = nil
			@user.save!(:validate => false)
			signin_in @user
			flash[:success] = "Your registration is complete"
			redirect_to @user
		else
			redirect_to root_path
		end
	end

	def check_whether_correct_user
		@user = User.find_by_id(params[:id])
		redirect_to root_path unless @user == current_user
	end

	def check_whether_admin
		redirect_to root_path unless current_user.admin?
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { :size => 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://www.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
		image_tag(gravatar_url, alt:user.name, class:"gravatar")
	end
end

app/views/users/_follow_form.html.erb
<%= form_for current_user.relationships.build(followed_id:@user.id), remote:true do |f| %>
	<%= f.hidden_field :followed_id %>
	<%= f.submit "follow",class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_unfollow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_unfollow">
		<% if current_user.following?(@user) %>
			<%= render 'unfollow_form' %>
		<% else %>
			<%= render 'follow_form' %>
		<% end %>
	</div>
<% end %>

app/views/users/_unfollow_form.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user.id), html: { method:"delete" }, remote:true do |f| %>
	<%= f.submit "unfollow",class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for(user, :size => 52 ) %>
	<%= link_to user.name, user_path(user) %>
	<% if current_user.admin? && !current_user?(user) %>
	  	| <%= link_to("delete", user_path(user), method:"delete", data: { confirm: "Are you sure?" }) unless user.admin? %>
	<% end %>
</li>

app/views/users/edit.html.erb
<%= provide(:title, 'Edit user') %>
<h1>Edit user</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/errors', object:f.object %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>
				
			<%= f.label :password_confirmation, "Confirm password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit("Update") %>
		<% end %>

		<%= link_to "Change", "http://gravatar.com/emails" %>
	<div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate @users %>
<ul class="users">	
	<%= render @users  %>	
</ul>
<%= will_paginate @users %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign Up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/errors', object:f.object %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>
				
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit("Create new user") %>
		<% end %>
	<div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% content_for :head, auto_discovery_link_tag(:atom, user_url(@user, format: "atom")) %>
 <div class="row">
  <aside class="span4">
	<section>
	  <h1>
	    <%= gravatar_for @user %>
	    <%= @user.name %>
	  </h1>
	</section>
	<section>
	        <%= render 'shared/stats' %>
	</section>
  </aside>
  
  	<%= render 'follow_unfollow_form' if signed_in? %>
	<%= link_to image_tag("feed-icon-28x28.png", class:"feedimage"),
											 user_url(@user, format: "atom") %>
	<% if @user.microposts.any? %> 
		<div class="span8">
			<h3>Microposts(<%= @user.microposts.count %>)</h3>
			<ol class="microposts">
				<%= render @microposts %>
			</ol>
			<%= will_paginate @microposts %>
		</div>
	<% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
	<section>
	  <h1>
	    <%= gravatar_for @user %>
	    <%= @user.name %>
	  </h1>
	</section>
	<section>
	        <%= render 'shared/stats' %>
	</section>
	<section>
		<% if @users.any? %>
		<div class="user_avatars">
			<% @users.each do |user| %>
			<%= link_to gravatar_for(user, size:30), user %>
			<% end %>
		</div>
		<% end %>
	</section>
  </aside>
<% if @users.any? %>
	<div class="span8">
		<h3><%= @title %></h3>
		<ul class="users">
			<%= render @users %>
		</ul>
		<%= will_paginate @users %>
	</div>
<% end %>
</div>